version: '3.9'

services:
    app:
        image: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
        networks:
            - proxy_network
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
            - ${RSOCKET_PORT}:${RSOCKET_PORT}
        environment:
            KEYSPACE_NAME: ${KEYSPACE_NAME}
            CASSANDRA_HOST: ${CASSANDRA_HOST}
            CASSANDRA_PORT: ${CASSANDRA_PORT}
            CASSANDRA_KEYSPACE: ${CASSANDRA_KEYSPACE}
            REQUEST_TIMEOUT_FOR_CASSANDRA: ${REQUEST_TIMEOUT_FOR_CASSANDRA}
            CONNECTION_TIMEOUT_FOR_CASSANDRA: ${CONNECTION_TIMEOUT_FOR_CASSANDRA}
            INIT_QUERY_TIMEOUT_FOR_CASSANDRA: ${INIT_QUERY_TIMEOUT_FOR_CASSANDRA}

            SERVER_PORT: ${SERVER_PORT}
            RSOCKET_PORT: ${RSOCKET_PORT}

            KAFKA_BROKER: ${KAFKA_BROKER}
            GROUP_ID_FOR_KAFKA: ${GROUP_ID_FOR_KAFKA}

            REDIS_PASSWORD: ${REDIS_PASSWORD}
            REDIS_CLIENT_NAME: ${REDIS_CLIENT_NAME}

        deploy:
            replicas: ${REPLICAS}
            placement:
                constraints: [node.labels.mgmt != true ]

networks:
    proxy_network:
        external: true
