version: '3.9'

services:
    app:
        image: $CI_REGISTRY/$CI_PROJECT_PATH:${CI_COMMIT_SHORT_SHA}-${CI_COMMIT_REF_NAME}
        networks:
            - proxy_network
        ports:
            - ${RSOCKET_PORT}:${RSOCKET_PORT}

        environment:
            SERVER_PORT: ${SERVER_PORT}
            SERVER_ADDR: ${SERVER_ADDR}
            RSOCKET_PORT: ${RSOCKET_PORT}

            KAFKA_BROKER: ${KAFKA_BROKER}
            GROUP_ID_FOR_KAFKA: ${GROUP_ID_FOR_KAFKA}

            ACTIVE_TASK: ${ACTIVE_TASK}
            NOTIFICATION: ${NOTIFICATION}
            CAR_TOTAL_DATA: ${CAR_TOTAL_DATA}

            CASSANDRA_DC: ${CASSANDRA_DC}
            KEYSPACE_NAME: ${KEYSPACE_NAME}
            CASSANDRA_PORT: ${CASSANDRA_PORT}
            CASSANDRA_HOST: ${CASSANDRA_HOST}

            CHAT_SERVICE_DOMAIN: ${CHAT_SERVICE_DOMAIN}
            CHAT_SERVICE_PREFIX: ${CHAT_SERVICE_PREFIX}

            CASSANDRA_MAX_REQ: ${CASSANDRA_MAX_REQ}

            CASSANDRA_MAX_CONN_LOCAL: ${CASSANDRA_MAX_CONN_LOCAL}
            CASSANDRA_MAX_CONN_REMOTE: ${CASSANDRA_MAX_CONN_REMOTE}

            CASSANDRA_CORE_CONN_LOCAL: ${CASSANDRA_CORE_CONN_LOCAL}
            CASSANDRA_CORE_CONN_REMOTE: ${CASSANDRA_CORE_CONN_REMOTE}

            REQUEST_TIMEOUT_FOR_CASSANDRA: ${REQUEST_TIMEOUT_FOR_CASSANDRA}
            CONNECTION_TIMEOUT_FOR_CASSANDRA: ${CONNECTION_TIMEOUT_FOR_CASSANDRA}
            INIT_QUERY_TIMEOUT_FOR_CASSANDRA: ${INIT_QUERY_TIMEOUT_FOR_CASSANDRA}

            SOS_TOPIC: ${SOS_TOPIC}
            SOS_TOPIC_FOR_ANDROID_NOTIFICATION: ${SOS_TOPIC_FOR_ANDROID_NOTIFICATION}

        deploy:
            replicas: ${REPLICAS}

networks:
    proxy_network:
        external: true
