version: '3.9'

services:
    app:
        image: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
        networks:
            - proxy_network
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
            - ${RSOCKET_PORT}:${RSOCKET_PORT}
        environment:
            SERVER_PORT: ${SERVER_PORT}
            RSOCKET_PORT: ${RSOCKET_PORT}
            KAFKA_BROKER: ${KAFKA_BROKER}

        deploy:
            replicas: ${REPLICAS}
            placement:
                constraints: [node.labels.mgmt != true ]

networks:
    proxy_network:
        external: true
