server:
    port: 9090
    address: localhost

spring:
    data:
        cassandra:
            port: 9942
            keyspace-name: SSD.TABLETS
            contact-points: 10.254.5.2
            local-datacenter: datacenter1
            schema-action: CREATE_IF_NOT_EXISTS

            request:
                timeout: 10s

            connection:
                connect-timeout: 10s
                init-query-timeout: 10s

        kafka:
            bootstrap-servers: 10.254.1.209:9092, 10.254.1.211:9092, 10.254.1.212:9092

            producer:
                key-serializer: org.apache.kafka.common.serialization.StringSerializer
                value-serializer: org.apache.kafka.common.serialization.StringSerializer

            consumer:
                group-id: SSD.GPS.TABLETS
                auto-offset-reset: earliest
                key-deserializer: org.apache.kafka.common.serialization.StringSerializer
                value-deserializer: org.apache.kafka.common.serialization.StringSerializer

            admin:
                client-id: SSD.GPS.TABLETS

    rsocket:
        server:
            port: 6060
            address: localhost

    redis:
        port: 6367
        host: 10.254.1.227
        password: 8tRk62
        client-name: default

variables:
    REDIS_HOST: 10.254.1.227
    REDIS_PORT: 6367
    REDIS_PASSWORD: 8tRk62
    REDIS_CLIENT_NAME: default

    KAFKA_BROKER: 10.254.1.209:9092, 10.254.1.211:9092, 10.254.1.212:9092
    GROUP_ID_FOR_KAFKA: SSD.GPS.TABLETS

    CASSANDRA_PORT: 9942
    CASSANDRA_HOST: 10.254.5.2