server:
    port: ${SERVER_PORT}
    address: ${SERVER_ADDR}

spring:
    data:
        cassandra:
            port: ${CASSANDRA_PORT}
            keyspace-name: ${KEYSPACE_NAME}
            contact-points: ${CASSANDRA_HOST}
            local-datacenter: ${CASSANDRA_DC}
            schema-action: CREATE_IF_NOT_EXISTS

        request:
            timeout: ${REQUEST_TIMEOUT_FOR_CASSANDRA}
            consistency: quorum

        connection:
            connect-timeout: ${CONNECTION_TIMEOUT_FOR_CASSANDRA}
            init-query-timeout: ${INIT_QUERY_TIMEOUT_FOR_CASSANDRA}

    rsocket:
        server:
            port: ${RSOCKET_PORT}
            address: ${SERVER_ADDR}

variables:
    KAFKA_BROKER : ${KAFKA_BROKER}
    GROUP_ID_FOR_KAFKA : ${GROUP_ID_FOR_KAFKA}

    SOS_TOPIC: sos_topic
    ACTIVE_TASK: ${ACTIVE_TASK}
    NOTIFICATION: ${NOTIFICATION}
    CAR_TOTAL_DATA: ${CAR_TOTAL_DATA}

    CASSANDRA_PORT: ${CASSANDRA_PORT}
    CASSANDRA_HOST: ${CASSANDRA_HOST}

    CASSANDRA_MAX_CONN_LOCAL: 10
    CASSANDRA_MAX_CONN_REMOTE: 4
    CASSANDRA_CORE_CONN_LOCAL: 4
    CASSANDRA_CORE_CONN_REMOTE: 2

    CHAT_SERVICE_DOMAIN : ${CHAT_SERVICE_DOMAIN}
    CHAT_SERVICE_PREFIX : ${CHAT_SERVICE_PREFIX}