
server:
    port: ${SERVER_PORT} # all trackers are going to send its data by its  port
    address: ${SERVER_ADDRESS}

spring:
    rsocket:
        server:
            port: ${RSOCKET_PORT}
            address: ${SERVER_ADDRESS}