package com.ssd.mvd.gpstabletsservice.constants;

public enum Countries {
    INDIA, CHINA, KAZAKHSTAN, UZBEKISTAN, RUSSIA, KIRGHIZIA, PAKISTAN, TAJIKISTAN, AFGHANISTAN,
    TURKEY, AZERBAIJAN, ARMENIA, TURKMENISTAN,
    BELORUSSIA, MONGOLIA, IRAN
}
